# Localhost

# GET ALL
GET http://localhost:8080/ingredients

###

# GET BY ID
GET http://localhost:8080/ingredients/666c0efea937734419ccfec8

###

# Create Contacts
POST http://localhost:8080/ingredients/create HTTP/1.1
Content-Type: application/json

{
    "congoleseName": "Mwaba Gaji",
    "frenchName": "Le Brout",
    "englishName": "palm nut soup",
    "otherName": "sauce graine ",
    "cuisine": "African",
    "description": "do this",
    "ingredient": "something",
    "instruction": "do this, do that",
    "cookingTime": "4h",
    "serving": "4",
    "videoLink": "somewhere"
}

###

# Put Contanct
PUT http://localhost:8080/ingredients/666385f84e95e0c336a58d40 HTTP/1.1
Content-Type: application/json

{
    "serving": "4"
}

###
# DeleteContact
DELETE http://localhost:8080/ingredients/666b4505fa27ec851461010d HTTP/1.1

# Production

###
# GET ALL
GET https://web-services-apis.onrender.com/ingredients

###
# GET BY ID
GET https://web-services-apis.onrender.com/ingredients/6668cbd6e5ba49ec9d0ca93d


###

# Create Contacts
POST https://web-services-apis.onrender.com/ingredients  HTTP/1.1
content-type: application/json

{
    "congoleseName": "Mwaba Gaji",
    "frenchName": "Le Brout",
    "englishName": "palm nut soup",
    "otherName": "sauce graine ",
    "cuisine": "African",
    "description": "do this",
    "ingredient": "something",
    "instruction": "do this, do that",
    "cookingTime": "4h",
    "serving": "4",
    "videoLink": "somewhere"
}

###

# Put Contanct
PUT https://web-services-apis.onrender.com/ingredients/id-to-modify/666385f84e95e0c336a58d40 HTTP/1.1
Content-Type: application/json

{
    "favoriteColor": "Blue"
}

###
# DeleteContact
DELETE https://web-services-apis.onrender.com/ingredients/6668ba0e83fc530950d5798d HTTP/1.1
